import { log } from "console";
import { LogOut } from "lucide-react";

export const players_data = [
  {
    player_id: 1,
    firstname: "LeBron",
    lastname: "James",
    birth_date: "1984-12-30",
    birth_country: "USA",
    nba_start: 2003,
    nba_pro: 18,
    height_feet: 6,
    height_inches: 9,
    height_meters: "2.06",
    weight_pounds: 250,
    weight_kilograms: "113.4",
    college: "St. Vincent-St. Mary HS (OH)",
    affiliation: "St. Vincent-St. Mary HS (OH)/USA",
    jersey: 6,
    active: true,
    position: "Forward",
  },
  {
    player_id: 2,
    firstname: "Stephen",
    lastname: "Curry",
    birth_date: "1988-03-14",
    birth_country: "USA",
    nba_start: 2009,
    nba_pro: 12,
    height_feet: 6,
    height_inches: 3,
    height_meters: "1.91",
    weight_pounds: 185,
    weight_kilograms: "83.9",
    college: "Davidson College",
    affiliation: "Davidson College/USA",
    jersey: 30,
    active: true,
    position: "Guard",
  },
  {
    player_id: 3,
    firstname: "Kevin",
    lastname: "Durant",
    birth_date: "1988-09-29",
    birth_country: "USA",
    nba_start: 2007,
    nba_pro: 14,
    height_feet: 6,
    height_inches: 10,
    height_meters: "2.08",
    weight_pounds: 240,
    weight_kilograms: "108.9",
    college: "University of Texas",
    affiliation: "University of Texas/USA",
    jersey: 7,
    active: true,
    position: "Forward",
  },
  {
    player_id: 4,
    firstname: "Giannis",
    lastname: "Antetokounmpo",
    birth_date: "1994-12-06",
    birth_country: "Greece",
    nba_start: 2013,
    nba_pro: 8,
    height_feet: 6,
    height_inches: 11,
    height_meters: "2.11",
    weight_pounds: 242,
    weight_kilograms: "109.8",
    college: "Filathlitikos (Greece)",
    affiliation: "Filathlitikos (Greece)/Greece",
    jersey: 34,
    active: true,
    position: "Forward",
  },
  {
    player_id: 5,
    firstname: "Kawhi",
    lastname: "Leonard",
    birth_date: "1991-06-29",
    birth_country: "USA",
    nba_start: 2011,
    nba_pro: 10,
    height_feet: 6,
    height_inches: 7,
    height_meters: "2.01",
    weight_pounds: 230,
    weight_kilograms: "104.3",
    college: "San Diego State University",
    affiliation: "San Diego State University/USA",
    jersey: 2,
    active: true,
    position: "Forward",
  },
  {
    player_id: 6,
    firstname: "Luka",
    lastname: "Dončić",
    birth_date: "1999-02-28",
    birth_country: "Slovenia",
    nba_start: 2018,
    nba_pro: 3,
    height_feet: 6,
    height_inches: 7,
    height_meters: "2.01",
    weight_pounds: 230,
    weight_kilograms: "104.3",
    college: "Real Madrid",
    affiliation: "Real Madrid/Slovenia",
    jersey: 77,
    active: true,
    position: "Guard",
  },
  {
    player_id: 7,
    firstname: "James",
    lastname: "Harden",
    birth_date: "1989-08-26",
    birth_country: "USA",
    nba_start: 2009,
    nba_pro: 12,
    height_feet: 6,
    height_inches: 5,
    height_meters: "1.96",
    weight_pounds: 220,
    weight_kilograms: "99.8",
    college: "Arizona State University",
    affiliation: "Arizona State University/USA",
    jersey: 13,
    active: true,
    position: "Guard",
  },
  {
    player_id: 8,
    firstname: "Anthony",
    lastname: "Davis",
    birth_date: "1993-03-11",
    birth_country: "USA",
    nba_start: 2012,
    nba_pro: 9,
    height_feet: 6,
    height_inches: 10,
    height_meters: "2.08",
    weight_pounds: 253,
    weight_kilograms: "114.8",
    college: "University of Kentucky",
    affiliation: "University of Kentucky/USA",
    jersey: 3,
    active: true,
    position: "Forward",
  },
  {
    player_id: 9,
    firstname: "Joel",
    lastname: "Embiid",
    birth_date: "1994-03-16",
    birth_country: "Cameroon",
    nba_start: 2014,
    nba_pro: 7,
    height_feet: 7,
    height_inches: 0,
    height_meters: "2.13",
    weight_pounds: 280,
    weight_kilograms: "127.0",
    college: "University of Kansas",
    affiliation: "University of Kansas/Cameroon",
    jersey: 21,
    active: true,
    position: "Center",
  },
  {
    player_id: 10,
    firstname: "Devin",
    lastname: "Booker",
    birth_date: "1996-10-30",
    birth_country: "USA",
    nba_start: 2015,
    nba_pro: 6,
    height_feet: 6,
    height_inches: 5,
    height_meters: "1.96",
    weight_pounds: 206,
    weight_kilograms: "93.4",
    college: "University of Kentucky",
    affiliation: "University of Kentucky/USA",
    jersey: 1,
    active: true,
    position: "Guard",
  },
  {
    player_id: 11,
    firstname: "Jayson",
    lastname: "Tatum",
    birth_date: "1998-03-03",
    birth_country: "USA",
    nba_start: 2017,
    nba_pro: 4,
    height_feet: 6,
    height_inches: 8,
    height_meters: "2.03",
    weight_pounds: 210,
    weight_kilograms: "95.3",
    college: "Duke University",
    affiliation: "Duke University/USA",
    jersey: 0,
    active: true,
    position: "Forward",
  },
  {
    player_id: 12,
    firstname: "Chris",
    lastname: "Paul",
    birth_date: "1985-05-06",
    birth_country: "USA",
    nba_start: 2005,
    nba_pro: 16,
    height_feet: 6,
    height_inches: 1,
    height_meters: "1.85",
    weight_pounds: 175,
    weight_kilograms: "79.4",
    college: "Wake Forest University",
    affiliation: "Wake Forest University/USA",
    jersey: 3,
    active: true,
    position: "Guard",
  },
];
export const teams_data = [
  {
    team_id: 1610612737,
    full_name: "Atlanta Hawks",
    logo: "https://upload.wikimedia.org/wikipedia/fr/e/ee/Hawks_2016.png",
    abbreviation: "ATL",
    nickname: "Hawks",
    city: "Atlanta",
    state: "Georgia",
    year_founded: 1949,
  },
  {
    team_id: 1610612738,
    full_name: "Boston Celtics",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    abbreviation: "BOS",
    nickname: "Celtics",
    city: "Boston",
    state: "Massachusetts",
    year_founded: 1946,
  },
  {
    team_id: 1610612739,
    full_name: "Cleveland Cavaliers",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    abbreviation: "CLE",
    nickname: "Cavaliers",
    city: "Cleveland",
    state: "Ohio",
    year_founded: 1970,
  },
  {
    team_id: 1610612740,
    full_name: "New Orleans Pelicans",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/2/21/New_Orleans_Pelicans.png/200px-New_Orleans_Pelicans.png",
    abbreviation: "NOP",
    nickname: "Pelicans",
    city: "New Orleans",
    state: "Louisiana",
    year_founded: 2002,
  },
  {
    team_id: 1610612741,
    full_name: "Chicago Bulls",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d1/Bulls_de_Chicago_logo.svg/1200px-Bulls_de_Chicago_logo.svg.png",
    abbreviation: "CHI",
    nickname: "Bulls",
    city: "Chicago",
    state: "Illinois",
    year_founded: 1966,
  },
  {
    team_id: 1610612742,
    full_name: "Dallas Mavericks",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b8/Mavericks_de_Dallas_logo.svg/150px-Mavericks_de_Dallas_logo.svg.png",
    abbreviation: "DAL",
    nickname: "Mavericks",
    city: "Dallas",
    state: "Texas",
    year_founded: 1980,
  },
  {
    team_id: 1610612743,
    full_name: "Denver Nuggets",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/3/35/Nuggets_de_Denver_2018.png/180px-Nuggets_de_Denver_2018.png",
    abbreviation: "DEN",
    nickname: "Nuggets",
    city: "Denver",
    state: "Colorado",
    year_founded: 1976,
  },
  {
    team_id: 1610612744,
    full_name: "Golden State Warriors",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/de/Warriors_de_Golden_State_logo.svg/1200px-Warriors_de_Golden_State_logo.svg.png",
    abbreviation: "GSW",
    nickname: "Warriors",
    city: "Golden State",
    state: "California",
    year_founded: 1946,
  },
  {
    team_id: 1610612745,
    full_name: "Houston Rockets",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/de/Houston_Rockets_logo_2003.png/330px-Houston_Rockets_logo_2003.png",
    abbreviation: "HOU",
    nickname: "Rockets",
    city: "Houston",
    state: "Texas",
    year_founded: 1967,
  },
  {
    team_id: 1610612746,
    full_name: "Los Angeles Clippers",
    logo: "https://upload.wikimedia.org/wikipedia/fr/d/d6/Los_Angeles_Clippers_logo_2010.png",
    abbreviation: "LAC",
    nickname: "Clippers",
    city: "Los Angeles",
    state: "California",
    year_founded: 1970,
  },
  {
    team_id: 1610612747,
    full_name: "Los Angeles Lakers",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/220px-Los_Angeles_Lakers_logo.svg.png",
    abbreviation: "LAL",
    nickname: "Lakers",
    city: "Los Angeles",
    state: "California",
    year_founded: 1948,
  },
  {
    team_id: 1610612748,
    full_name: "Miami Heat",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/1/1c/Miami_Heat_-_Logo.svg/1200px-Miami_Heat_-_Logo.svg.png",
    abbreviation: "MIA",
    nickname: "Heat",
    city: "Miami",
    state: "Florida",
    year_founded: 1988,
  },
  {
    team_id: 1610612749,
    full_name: "Milwaukee Bucks",
    logo: "https://upload.wikimedia.org/wikipedia/fr/3/34/Bucks2015.png",
    abbreviation: "MIL",
    nickname: "Bucks",
    city: "Milwaukee",
    state: "Wisconsin",
    year_founded: 1968,
  },
  {
    team_id: 1610612750,
    full_name: "Minnesota Timberwolves",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d9/Timberwolves_du_Minnesota_logo_2017.png/200px-Timberwolves_du_Minnesota_logo_2017.png",
    abbreviation: "MIN",
    nickname: "Timberwolves",
    city: "Minnesota",
    state: "Minnesota",
    year_founded: 1989,
  },
  {
    team_id: 1610612751,
    full_name: "Brooklyn Nets",
    abbreviation: "BKN",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Brooklyn_Nets_newlogo.svg/130px-Brooklyn_Nets_newlogo.svg.png",
    nickname: "Nets",
    city: "Brooklyn",
    state: "New York",
    year_founded: 1976,
  },
  {
    team_id: 1610612752,
    full_name: "New York Knicks",
    logo: "https://upload.wikimedia.org/wikipedia/fr/3/34/Knicks_de_NY.png",
    abbreviation: "NYK",
    nickname: "Knicks",
    city: "New York",
    state: "New York",
    year_founded: 1946,
  },
  {
    team_id: 1610612753,
    full_name: "Orlando Magic",
    logo: "https://upload.wikimedia.org/wikipedia/fr/b/bd/Orlando_Magic_logo_2010.png",
    abbreviation: "ORL",
    nickname: "Magic",
    city: "Orlando",
    state: "Florida",
    year_founded: 1989,
  },
  {
    team_id: 1610612754,
    full_name: "Indiana Pacers",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/c/cf/Pacers_de_l%27Indiana_logo.svg/1180px-Pacers_de_l%27Indiana_logo.svg.png",
    abbreviation: "IND",
    nickname: "Pacers",
    city: "Indiana",
    state: "Indiana",
    year_founded: 1976,
  },
  {
    team_id: 1610612755,
    full_name: "Philadelphia 76ers",
    logo: "https://upload.wikimedia.org/wikipedia/fr/4/48/76ers_2016.png",
    abbreviation: "PHI",
    nickname: "76ers",
    city: "Philadelphia",
    state: "Pennsylvania",
    year_founded: 1949,
  },
  {
    team_id: 1610612756,
    full_name: "Phoenix Suns",
    logo: "https://upload.wikimedia.org/wikipedia/fr/5/56/Phoenix_Suns_2013.png",
    abbreviation: "PHX",
    nickname: "Suns",
    city: "Phoenix",
    state: "Arizona",
    year_founded: 1968,
  },
  {
    team_id: 1610612757,
    full_name: "Portland Trail Blazers",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Portland_Trail_Blazers_logo.svg/1200px-Portland_Trail_Blazers_logo.svg.png",
    abbreviation: "POR",
    nickname: "Trail Blazers",
    city: "Portland",
    state: "Oregon",
    year_founded: 1970,
  },
  {
    team_id: 1610612758,
    full_name: "Sacramento Kings",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/9/95/Kings_de_Sacramento_logo.svg/1200px-Kings_de_Sacramento_logo.svg.png",
    abbreviation: "SAC",
    nickname: "Kings",
    city: "Sacramento",
    state: "California",
    year_founded: 1948,
  },
  {
    team_id: 1610612759,
    full_name: "San Antonio Spurs",
    logo: "https://upload.wikimedia.org/wikipedia/fr/0/0e/San_Antonio_Spurs_2018.png",
    abbreviation: "SAS",
    nickname: "Spurs",
    city: "San Antonio",
    state: "Texas",
    year_founded: 1976,
  },
  {
    team_id: 1610612760,
    full_name: "Oklahoma City Thunder",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/4/4f/Thunder_d%27Oklahoma_City_logo.svg/1200px-Thunder_d%27Oklahoma_City_logo.svg.png",
    abbreviation: "OKC",
    nickname: "Thunder",
    city: "Oklahoma City",
    state: "Oklahoma",
    year_founded: 1967,
  },
  {
    team_id: 1610612761,
    full_name: "Toronto Raptors",
    logo: "https://upload.wikimedia.org/wikipedia/fr/8/89/Raptors2015.png",
    abbreviation: "TOR",
    nickname: "Raptors",
    city: "Toronto",
    state: "Ontario",
    year_founded: 1995,
  },
  {
    team_id: 1610612762,
    full_name: "Utah Jazz",
    logo: "https://upload.wikimedia.org/wikipedia/fr/3/3b/Jazz_de_l%27Utah_logo.png",
    abbreviation: "UTA",
    nickname: "Jazz",
    city: "Utah",
    state: "Utah",
    year_founded: 1974,
  },
  {
    team_id: 1610612763,
    full_name: "Memphis Grizzlies",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Memphis_Grizzlies.svg/1200px-Memphis_Grizzlies.svg.png",
    abbreviation: "MEM",
    nickname: "Grizzlies",
    city: "Memphis",
    state: "Tennessee",
    year_founded: 1995,
  },
  {
    team_id: 1610612764,
    full_name: "Washington Wizards",
    logo: "https://upload.wikimedia.org/wikipedia/fr/archive/d/d6/20161212034849%21Wizards2015.png",
    abbreviation: "WAS",
    nickname: "Wizards",
    city: "Washington",
    state: "District of Columbia",
    year_founded: 1961,
  },
  {
    team_id: 1610612765,
    full_name: "Detroit Pistons",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Logo_of_the_Detroit_Pistons.png/300px-Logo_of_the_Detroit_Pistons.png",
    abbreviation: "DET",
    nickname: "Pistons",
    city: "Detroit",
    state: "Michigan",
    year_founded: 1948,
  },
  {
    team_id: 1610612766,
    full_name: "Charlotte Hornets",
    logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f3/Hornets_de_Charlotte_logo.svg/1200px-Hornets_de_Charlotte_logo.svg.png",
    abbreviation: "CHA",
    nickname: "Hornets",
    city: "Charlotte",
    state: "North Carolina",
    year_founded: 1988,
  },
];
