// const { v4: uuidv4 } = require("uuid");

export const players_data = [
  {
    family_name: "James",
    given_name: "Lebron",
    stats: {
      ppg: 25.5,
      apg: 8.7,
      rpg: 7.9,
      plus_minus: 10,
      cicero_score: 95,
    },
    position: "Forward",
    hometown: "Akron, OH",
  },
  {
    family_name: "Curry",
    given_name: "Stephen",
    stats: {
      ppg: 30.2,
      apg: 6.5,
      rpg: 5.0,
      plus_minus: 8,
      cicero_score: 94,
    },
    position: "Guard",
    hometown: "Akron, OH",
  },
  {
    family_name: "Durant",
    given_name: "Kevin",
    stats: {
      ppg: 28.7,
      apg: 5.2,
      rpg: 8.3,
      plus_minus: 12,
      cicero_score: 92,
    },
    position: "Forward",
    hometown: "Washington, D.C.",
  },
  {
    family_name: "Antetokounmpo",
    given_name: "Giannis",
    stats: {
      ppg: 29.9,
      apg: 6.0,
      rpg: 11.0,
      plus_minus: 9,
      cicero_score: 91,
    },
    position: "Forward",
    hometown: "Athens, Greece",
  },
  {
    family_name: "Leonard",
    given_name: "Kawhi",
    stats: {
      ppg: 24.8,
      apg: 5.2,
      rpg: 6.5,
      plus_minus: 11,
      cicero_score: 93,
    },
    position: "Forward",
    hometown: "Los Angeles, CA",
  },
  {
    family_name: "Dončić",
    given_name: "Luka",
    stats: {
      ppg: 27.0,
      apg: 9.0,
      rpg: 8.6,
      plus_minus: 7,
      cicero_score: 90,
    },
    position: "Guard",
    hometown: "Ljubljana, Slovenia",
  },
  {
    family_name: "Harden",
    given_name: "James",
    stats: {
      ppg: 31.6,
      apg: 9.8,
      rpg: 6.5,
      plus_minus: 8,
      cicero_score: 94,
    },
    position: "Guard",
    hometown: "Los Angeles, CA",
  },
  {
    family_name: "Davis",
    given_name: "Anthony",
    stats: {
      ppg: 26.1,
      apg: 3.1,
      rpg: 9.3,
      plus_minus: 10,
      cicero_score: 91,
    },
    position: "Forward",
    hometown: "Chicago, IL",
  },
  {
    family_name: "Embiid",
    given_name: "Joel",
    stats: {
      ppg: 28.5,
      apg: 4.2,
      rpg: 11.1,
      plus_minus: 9,
      cicero_score: 92,
    },
    position: "Center",
    hometown: "Yaoundé, Cameroon",
  },
  {
    family_name: "Booker",
    given_name: "Devin",
    stats: {
      ppg: 26.6,
      apg: 4.3,
      rpg: 4.2,
      plus_minus: 6,
      cicero_score: 89,
    },
    position: "Guard",
    hometown: "Grand Rapids, MI",
  },
  {
    family_name: "Tatum",
    given_name: "Jayson",
    stats: {
      ppg: 24.3,
      apg: 4.2,
      rpg: 7.0,
      plus_minus: 5,
      cicero_score: 88,
    },
    position: "Forward",
    hometown: "St. Louis, MO",
  },
  {
    family_name: "Paul",
    given_name: "Chris",
    stats: {
      ppg: 16.4,
      apg: 8.9,
      rpg: 4.5,
      plus_minus: 7,
      cicero_score: 90,
    },
    position: "Guard",
    hometown: "Winston-Salem, NC",
  },
];
