const players = [
  {
    id: 1,
    name: "LeBron James",
    stats: {
      ppg: 25.5,
      apg: 8.7,
      rpg: 7.9,
      plusMinus: 10,
      ciceroScore: 95,
    },
    position: "Forward",
    hometown: "Akron, OH",
  },
  {
    id: 2,
    name: "Stephen Curry",
    stats: {
      ppg: 30.2,
      apg: 6.5,
      rpg: 5.0,
      plusMinus: 8,
      ciceroScore: 94,
    },
    position: "Guard",
    hometown: "Akron, OH",
  },
  {
    id: 3,
    name: "Kevin Durant",
    stats: {
      ppg: 28.7,
      apg: 5.2,
      rpg: 8.3,
      plusMinus: 12,
      ciceroScore: 92,
    },
    position: "Forward",
    hometown: "Washington, D.C.",
  },
  {
    id: 4,
    name: "Giannis Antetokounmpo",
    stats: {
      ppg: 29.9,
      apg: 6.0,
      rpg: 11.0,
      plusMinus: 9,
      ciceroScore: 91,
    },
    position: "Forward",
    hometown: "Athens, Greece",
  },
  {
    id: 5,
    name: "Kawhi Leonard",
    stats: {
      ppg: 24.8,
      apg: 5.2,
      rpg: 6.5,
      plusMinus: 11,
      ciceroScore: 93,
    },
    position: "Forward",
    hometown: "Los Angeles, CA",
  },
  {
    id: 6,
    name: "Luka Dončić",
    stats: {
      ppg: 27.0,
      apg: 9.0,
      rpg: 8.6,
      plusMinus: 7,
      ciceroScore: 90,
    },
    position: "Guard",
    hometown: "Ljubljana, Slovenia",
  },
  {
    id: 7,
    name: "James Harden",
    stats: {
      ppg: 31.6,
      apg: 9.8,
      rpg: 6.5,
      plusMinus: 8,
      ciceroScore: 94,
    },
    position: "Guard",
    hometown: "Los Angeles, CA",
  },
  {
    id: 8,
    name: "Anthony Davis",
    stats: {
      ppg: 26.1,
      apg: 3.1,
      rpg: 9.3,
      plusMinus: 10,
      ciceroScore: 91,
    },
    position: "Forward",
    hometown: "Chicago, IL",
  },
  {
    id: 9,
    name: "Joel Embiid",
    stats: {
      ppg: 28.5,
      apg: 4.2,
      rpg: 11.1,
      plusMinus: 9,
      ciceroScore: 92,
    },
    position: "Center",
    hometown: "Yaoundé, Cameroon",
  },
  {
    id: 10,
    name: "Devin Booker",
    stats: {
      ppg: 26.6,
      apg: 4.3,
      rpg: 4.2,
      plusMinus: 6,
      ciceroScore: 89,
    },
    position: "Guard",
    hometown: "Grand Rapids, MI",
  },
  {
    id: 11,
    name: "Jayson Tatum",
    stats: {
      ppg: 24.3,
      apg: 4.2,
      rpg: 7.0,
      plusMinus: 5,
      ciceroScore: 88,
    },
    position: "Forward",
    hometown: "St. Louis, MO",
  },
  {
    id: 12,
    name: "Chris Paul",
    stats: {
      ppg: 16.4,
      apg: 8.9,
      rpg: 4.5,
      plusMinus: 7,
      ciceroScore: 90,
    },
  },
];
